<?php

$crudPermissions = fn (string $codePrefix, string $featureName, string $module, string $route): array => [
    [
        'code' => "{$codePrefix}.view",
        'name' => "Lihat {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'view',
    ],
    [
        'code' => "{$codePrefix}.create",
        'name' => "Tambah {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'create',
    ],
    [
        'code' => "{$codePrefix}.update",
        'name' => "Ubah {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'update',
    ],
    [
        'code' => "{$codePrefix}.delete",
        'name' => "Hapus {$featureName}",
        'module' => $module,
        'route' => $route,
        'action' => 'delete',
    ],
];

return [
    'permissions' => [
        [
            'code' => 'dashboard.view',
            'name' => 'Lihat Dashboard',
            'module' => 'Utama',
            'route' => 'dashboard',
            'action' => 'view',
        ],
        [
            'code' => 'documents.inbox.view',
            'name' => 'Lihat Inbox Approval',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.inbox',
            'action' => 'view',
        ],
        [
            'code' => 'documents.approval.view',
            'name' => 'Lihat Detail Approval Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.show',
            'action' => 'view',
        ],
        [
            'code' => 'documents.approval.download',
            'name' => 'Download File Approval Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.files.show',
            'action' => 'download',
        ],
        [
            'code' => 'documents.approval.preview',
            'name' => 'Preview File Approval Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.files.preview',
            'action' => 'preview',
        ],
        [
            'code' => 'documents.approval.generated',
            'name' => 'Preview Printout Approval Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.generated.show',
            'action' => 'preview',
        ],
        [
            'code' => 'documents.create.view',
            'name' => 'Lihat Tambah Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.create',
            'action' => 'view',
        ],
        [
            'code' => 'documents.create.drafts',
            'name' => 'Lihat Draft Dokumen Saya',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.create.drafts',
            'action' => 'view',
        ],
        [
            'code' => 'documents.create.drafts.edit',
            'name' => 'Edit Draft Dokumen Saya',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.create.drafts.edit',
            'action' => 'view',
        ],
        [
            'code' => 'documents.create.drafts.delete',
            'name' => 'Hapus Draft Dokumen Saya',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.create.drafts.destroy',
            'action' => 'delete',
        ],
        [
            'code' => 'documents.create.create',
            'name' => 'Submit Tambah Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.store',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.view',
            'name' => 'Lihat Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master',
            'action' => 'view',
        ],
        [
            'code' => 'documents.master.detail',
            'name' => 'Lihat Detail Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.show',
            'action' => 'view',
        ],
        [
            'code' => 'documents.master.download',
            'name' => 'Download File Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.files.show',
            'action' => 'download',
        ],
        [
            'code' => 'documents.master.preview',
            'name' => 'Preview File Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.files.preview',
            'action' => 'preview',
        ],
        [
            'code' => 'documents.master.generated',
            'name' => 'Preview Printout Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.generated.show',
            'action' => 'preview',
        ],
        [
            'code' => 'documents.master.imports.create',
            'name' => 'Import Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.imports.create',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.imports.create-level',
            'name' => 'Pilih Level Import Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.imports.create.level',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.imports.store',
            'name' => 'Simpan Import Dokumen Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.imports.store',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.imports.store-level',
            'name' => 'Simpan Import Dokumen Master per Level',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.imports.store.level',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.imports.edit',
            'name' => 'Edit Dokumen Imported',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.imports.edit',
            'action' => 'update',
        ],
        [
            'code' => 'documents.master.imports.update',
            'name' => 'Simpan Edit Dokumen Imported',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.imports.update',
            'action' => 'update',
        ],
        [
            'code' => 'documents.obsolete.view',
            'name' => 'Lihat Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete',
            'action' => 'view',
        ],
        [
            'code' => 'documents.obsolete.detail',
            'name' => 'Lihat Detail Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.show',
            'action' => 'view',
        ],
        [
            'code' => 'documents.obsolete.download',
            'name' => 'Download File Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.files.show',
            'action' => 'download',
        ],
        [
            'code' => 'documents.obsolete.preview',
            'name' => 'Preview File Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.files.preview',
            'action' => 'preview',
        ],
        [
            'code' => 'documents.obsolete.create',
            'name' => 'Tambah Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete',
            'action' => 'create',
        ],
        [
            'code' => 'documents.obsolete.restore',
            'name' => 'Jadikan Master Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.restore',
            'action' => 'restore',
        ],
        [
            'code' => 'documents.obsolete.imports.create',
            'name' => 'Import Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.imports.create',
            'action' => 'create',
        ],
        [
            'code' => 'documents.obsolete.imports.create-legacy',
            'name' => 'Import Dokumen Obsolete Legacy',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.imports.create.legacy',
            'action' => 'create',
        ],
        [
            'code' => 'documents.obsolete.imports.create-level',
            'name' => 'Pilih Level Import Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.imports.create.level',
            'action' => 'create',
        ],
        [
            'code' => 'documents.obsolete.imports.store',
            'name' => 'Simpan Import Dokumen Obsolete',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.imports.store',
            'action' => 'create',
        ],
        [
            'code' => 'documents.obsolete.imports.store-level',
            'name' => 'Simpan Import Dokumen Obsolete per Level',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.obsolete.imports.store.level',
            'action' => 'create',
        ],
        [
            'code' => 'documents.existing.imports.view',
            'name' => 'Lihat Arsip Dokumen Existing',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.index',
            'action' => 'view',
        ],
        [
            'code' => 'documents.existing.imports.numbering-setup',
            'name' => 'Setup Numbering Dokumen Existing',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.numbering-setups.store',
            'action' => 'create',
        ],
        [
            'code' => 'documents.existing.imports.number-reuse-check',
            'name' => 'Cek Penggunaan Nomor Dokumen Import',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.number-reuse-check',
            'action' => 'view',
        ],
        [
            'code' => 'documents.existing.imports.detail',
            'name' => 'Lihat Detail Arsip Dokumen Existing',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.show',
            'action' => 'view',
        ],
        [
            'code' => 'documents.existing.imports.delete',
            'name' => 'Hapus Dokumen Imported Existing',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.destroy',
            'action' => 'delete',
        ],
        [
            'code' => 'documents.existing.imports.revision',
            'name' => 'Ajukan Revisi Imported Existing Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.revisions.store',
            'action' => 'create',
        ],
        [
            'code' => 'documents.master.imported.obsolete',
            'name' => 'Obsolete Imported Existing Master',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.master.imported.obsolete',
            'action' => 'create',
        ],
        [
            'code' => 'documents.existing.imports.download',
            'name' => 'Download File Arsip Dokumen Existing',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.files.show',
            'action' => 'download',
        ],
        [
            'code' => 'documents.existing.imports.preview',
            'name' => 'Preview File Arsip Dokumen Existing',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.existing.imports.files.preview',
            'action' => 'preview',
        ],
        [
            'code' => 'documents.approval.assign',
            'name' => 'Assign Approver Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.assign',
            'action' => 'assign',
        ],
        [
            'code' => 'documents.approval.update-submitted',
            'name' => 'Edit Dokumen Sebelum Assign Approver',
            'module' => 'Manajemen Dokumen',
            'route' => 'documents.approval.update-submitted',
            'action' => 'update',
        ],
        [
            'code' => 'document-templates.view',
            'name' => 'Lihat Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'view',
        ],
        [
            'code' => 'document-templates.download',
            'name' => 'Download Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.files.show',
            'action' => 'download',
        ],
        [
            'code' => 'document-templates.edit',
            'name' => 'Edit Template Dokumen',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'edit',
        ],
        [
            'code' => 'document-templates.delete',
            'name' => 'Delete',
            'module' => 'Manajemen Dokumen',
            'route' => 'document-templates.index',
            'action' => 'delete',
        ],
        [
            'code' => 'reports.view',
            'name' => 'Lihat Reporting',
            'module' => 'Reporting',
            'route' => 'reports.index',
            'action' => 'view',
        ],
        ...$crudPermissions('users', 'User', 'Administrasi', 'users.index'),
        ...$crudPermissions('access-groups', 'Group Akses', 'Administrasi', 'access-groups.index'),
        [
            'code' => 'access-menus.view',
            'name' => 'Lihat Menu Akses',
            'module' => 'Administrasi',
            'route' => 'access-menus.index',
            'action' => 'view',
        ],
        ...$crudPermissions('approval-flows', 'Approval Flow', 'Administrasi', 'approval-flows.index'),
        ...$crudPermissions('master-data.process-functions', 'Proses / Fungsi', 'Master Data', 'master-data.process-functions'),
        ...$crudPermissions('master-data.business-processes', 'Proses Bisnis', 'Master Data', 'master-data.business-processes'),
        ...$crudPermissions('master-data.departments', 'Department', 'Master Data', 'master-data.departments'),
        ...$crudPermissions('master-data.document-types', 'Jenis Dokumen', 'Master Data', 'master-data.document-types'),
        [
            'code' => 'activity-log.view',
            'name' => 'Lihat Catatan Aktivitas',
            'module' => 'Log',
            'route' => 'activity-log.index',
            'action' => 'view',
        ],
    ],
];
